title : Kavya Podishetty
logo : assests/mypic.jpg
discription : Seeking for Data Scientist, Data Analyst, Machine Learning Engineer | Ex - Data Scientist Trainee at TuringMinds.ai
show_downloads : true

